# Flower-RPC ????????
# JVM ?? -D???=? ??????????

# ZooKeeper ?????
flower.rpc.zk.address=127.0.0.1:2181

# ???????????
flower.rpc.server.host=127.0.0.1
flower.rpc.server.port=9998

# SPI ?????
flower.rpc.registry=zk
flower.rpc.discovery=zk
flower.rpc.transport=netty

# ???????
flower.rpc.load-balance=consistent-hash

# ?????????
flower.rpc.serializer=kryo
flower.rpc.compress=none

# ????????
flower.rpc.connect-timeout-millis=3000
flower.rpc.request-timeout-millis=5000

# ?????
flower.rpc.heartbeat.interval-seconds=5
flower.rpc.heartbeat.timeout-seconds=15